version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker2
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - db_data:/var/lib/mysql

  www:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

volumes:
  db_data:
    # adicionar opções específicas para o volume, se necessário
